name: CI - DevSecOps Pipeline

on:
  push:
    branches: [main]

jobs:
  build-test-scan:
    name: Build, Test, and Scan Docker App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t todo-app:latest .

      # - name: Scan Docker Image with Trivy
      #   uses: aquasecurity/trivy-action@master
      #   with:
      #     image-ref: 'todo-app:latest'
      #     format: 'table'
      #     severity: 'CRITICAL,HIGH'

      - name: Scan Docker Image with Trivy (to file)
        run: |
         docker run --rm \
         -v /var/run/docker.sock:/var/run/docker.sock \
         -v $(pwd):/root/reports \
         aquasec/trivy:latest \
         image --severity CRITICAL,HIGH --format table -o /root/reports/trivy-report.txt todo-app:latest


      - name: Upload Trivy Scan Report (Optional)
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.txt
